apiVersion: apps/v1
kind: Deployment
metadata:
  name: apptransaction-deployment
  namespace: payapp-namespace
  labels:
   app: app-transaction
spec:
  minReadySeconds: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  replicas: 2
  selector:
    matchLabels:
         app: app-transaction
  template:
    metadata:
      labels:
        app: app-transaction
    spec: 
      containers:
      - name: app-transaction
        image: ordonezmaria1/app-transaction
        ports: 
          - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: apptransaction-service
  namespace: payapp-namespace
spec:
  selector:
    app: app-transaction
  ports:
   - protocol: TCP
     port: 8082
     targetPort: 8082
  type: LoadBalancer
